on:
  pull_request_target:
    types: [ opened ]

jobs:
  event_handler:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: python -m pip install requests
        shell: bash

      - name: handle event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/process_github_events.py
        shell: bash