name: test_coverage

on:
  push:
    branches:
    - dev
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:


jobs:
  test_coverage:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name:  build & install package
        run: |
          python -m pip install build
          python -m build
          find . -name "*.whl" -exec python -m pip install {}[test_full] ';'

      - name: clean environment
        run: |
          export backup_files=( tests examples .env_file makefile )
          mkdir /tmp/backup
          for i in "${backup_files[@]}" ; do mv "$i"  /tmp/backup ; done
          rm -rf ..?* .[!.]* *
          for i in "${backup_files[@]}" ; do mv  "/tmp/backup/$i"  .  ; done
          rm -rf /tmp/backup
          touch venv  # disable venv target

      - name: create session file
        run: echo "${{ secrets.TG_SESSION }}" | base64 --decode > anon.session
        shell: bash

      - name: set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-6

      - name: run tests
        env:
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        run: |
          make test
