name: test_coverage

on:
  push:
    branches:
    - dev
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:


jobs:
  test_coverage:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create gdf_account.json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "gdf_account.json"
          json: ${{ secrets.GDF_ACCOUNT_JSON }}

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install package
        run: |
          python -m pip install build
          python -m build
          find . -name "*.whl" -exec python -m pip install {}[test_full] ';'

      - name: prepare testing environment
        run: |
          export backup_files=( tests examples .env_file makefile )
          mkdir /tmp/backup
          for i in "${backup_files[@]}" ; do mv "$i"  /tmp/backup ; done
          rm -rf ..?* .[!.]* *
          for i in "${backup_files[@]}" ; do mv  "/tmp/backup/$i"  .  ; done
          rm -rf /tmp/backup
          touch venv  # disable venv target

      - name: run tests
        run: |
          make test
        shell: bash
        env:
          RASA_API_KEY: rasa
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          GDF_ACCOUNT_JSON: ./gdf_account.json
